### ISSUE TITLE
native conjugate() operation

### ISSUE THREAD

**Issue by evaleev** [ValeevGroup/tiledarray#34] opened 2015-10-11 21:00 UTC

**Comment by justusc** [comment] 2015-10-11 22:00
Are you referring to complex conjugate for tensors, arrays, or both?

**Comment by evaleev** [comment] 2015-10-11 22:20
for TiledArray::Array

**Comment by justusc** [comment] 2015-10-12 12:34
I think this would be best implemented with two free functions
```c++
template <typename T, unsigned int DIM, typename Tile, typename Policy>
Array<T, DIM, Tile, Policy> conjugate(const Array<T, DIM, Tile, Policy>& array);

template <typename T, unsigned int DIM, typename Tile, typename Policy>
Array<T, DIM, Tile, Policy>& inplace_conjugate(Array<T, DIM, Tile, Policy>& array);
```
which will be consistent with other mutating functions for Array. This will also require a new tile interface function:
```c++
template <typename T>
Tensor<T> conjugate(const Tensor<T>& tensor);

template <typename T>
Tensor<T>& conjugate_to(Tensor<T>& tensor);
```
These changes are easy to implement.

However, proper complex support is probably going to require some extra work. Specifically, we need to add expression support for complex operations. For example, if we want to:
```c++
C("m,n") += alpha * A("m,k) * B("n,k").conjagate();
```
To implement conjugate operations in expressions efficiently, i.e. without extra temporaries, we need to add many interface functions that incorporate this.

**Comment by shiozaki** [comment] 2015-11-24 03:01
Any updates?

Also I would like to be able to conjugate real array (which does not do anything). This is necessary to have one code for real and complex cases, and is consistent with what ScaLapack can do (for instance, "C" vs. "T" in dgemm)

**Comment by justusc** [comment] 2015-11-24 03:12
There is some progress here but it is not quite ready for use. I have implemented the code to compute the conjugate of tiles using a multiplicative operator.

I am currently working on other changes that have some crossover with this.

**Comment by shiozaki** [comment] 2015-11-30 23:56
just a reminder - one has to update squared_norm() (and similar functions) too so that it returns a norm. Currently it gives a wrong result (one of "arg" should be conjugated).
```
    /// \return The vector norm of this tensor
    numeric_type squared_norm() const {
      auto square_op = [] (numeric_type& restrict res, const numeric_type arg)
              { res += arg * arg; };
      auto sum_op = [] (numeric_type& restrict res, const numeric_type arg)
              { res += arg; };
      return reduce(square_op, sum_op, numeric_type(0));
    }
```

**Comment by justusc** [comment] 2015-12-10 16:38
I just pushed changes that include partial support for complex conjugate operations in expressions. To take the complex conjugate of an array in an expression, use the following interfaces:

```C++
C("i,j") =  alpha * A("i,k").conj() * B("k,j);
C("i,j") =  alpha * conj(A("i,k")) * B("k,j);
C("i,j") =  conj(alpha * A("i,k")) * B("k,j);
```
Currently, there is no support for complex conjugate of contraction, addition, subtraction, or scaled expressions. Support for these expression types is forthcoming.

Tile level support for complex conjugate operations is fully supported. Note that Tensor::norm() and Tensor::squared_norm() now correctly handle complex types.

@shiozaki The changes have been pushed but there are no unit tests so there may still be bugs in the code. Feel free to give it a try and and report any bugs here.

**Comment by shiozaki** [comment] 2015-12-10 17:05
Is this implemented for Block expressions? I am getting an error after update:
```
../../../src/smith/spinfreebase_update.cpp: In instantiation of 'std::shared_ptr<bagel::SMITH::MultiTATensor<DataType, 4> > bagel::SMITH::SpinFreeMethod<DataType>::update_amplitude(std::shared_ptr<bagel::SMITH::MultiTATensor<DataType, 4> >, std::shared_ptr<const bagel::SMITH::MultiTATensor<DataType, 4> >) const [with DataType = double]':
../../../src/smith/spinfreebase.cc:433:16:   required from here
../../../src/smith/spinfreebase_update.cpp:94:56: error: 'class TiledArray::expressions::BlkTsrExpr<const TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >' has no member named 'conj'
         (*tjst)("x0,a1,x2,a3") -= i0("o4,a1,a3") * 0.5 * (*s)("o4,x0,x2").conj();
```

**Comment by shiozaki** [comment] 2015-12-10 17:23
actually even without using the new function, I get errors that prevent me from compiling bagel with TA.
```
/usr/local/include/TiledArray/dist_eval/binary_eval.h: In instantiation of 'void TiledArray::detail::BinaryEvalImpl<Left, Right, Op, Policy>::eval_tile(TiledArray::detail::BinaryEvalImpl<Left, Right, Op, Policy>::size_type, L, R) [with L = TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >&; R = const TiledArray::ZeroTensor; Left = TiledArray::detail::DistEval<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy>; Right = TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::detail::UnaryWrapper<TiledArray::Shift<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, false> > >, TiledArray::DensePolicy>; Op = TiledArray::detail::BinaryWrapper<TiledArray::Mult<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, true, true> >; Policy = TiledArray::DensePolicy; TiledArray::detail::BinaryEvalImpl<Left, Right, Op, Policy>::size_type = long unsigned int]':
/usr/local/include/TiledArray/dist_eval/binary_eval.h:186:17:   required from 'int TiledArray::detail::BinaryEvalImpl<Left, Right, Op, Policy>::internal_eval() [with Left = TiledArray::detail::DistEval<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy>; Right = TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::detail::UnaryWrapper<TiledArray::Shift<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, false> > >, TiledArray::DensePolicy>; Op = TiledArray::detail::BinaryWrapper<TiledArray::Mult<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, true, true> >; Policy = TiledArray::DensePolicy]'
../../../src/smith/spinfreebase.cc:434:47:   required from here
/usr/local/include/TiledArray/dist_eval/binary_eval.h:124:32: error: no match for call to '(TiledArray::detail::BinaryEvalImpl<TiledArray::detail::DistEval<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::detail::UnaryWrapper<TiledArray::Shift<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, false> > >, TiledArray::DensePolicy>, TiledArray::detail::BinaryWrapper<TiledArray::Mult<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, true, true> >, TiledArray::DensePolicy>::op_type {aka TiledArray::detail::BinaryWrapper<TiledArray::Mult<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, true, true> >}) (TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >&, const TiledArray::ZeroTensor&)'
         DistEvalImpl_::set_tile(i, op_(left, right));
```

I believe this was introduced very recently.

**Comment by justusc** [comment] 2015-12-10 17:26
No, block expressions are not supported but it is on the list.

**Comment by shiozaki** [comment] 2015-12-10 17:28
PS: The second comment is not related to block expressions. You must have changed something in somewhere. This code was working as of a few days ago.

**Comment by justusc** [comment] 2015-12-10 17:30
Yes, it looks like it is related to recent changes. I am trying to determine the source of the error.

**Comment by shiozaki** [comment] 2015-12-10 17:32
FYI
```
In file included from /usr/local/include/TiledArray/expressions/add_engine.h:31:0,
                 from /usr/local/include/TiledArray/expressions/add_expr.h:29,
                 from /usr/local/include/TiledArray/expressions/tsr_expr.h:29,
                 from /usr/local/include/tiledarray.h:37,
                 from ../../../src/smith/tatensor.h:29,
                 from ../../../src/smith/tensor.h:45,
                 from ../../../src/smith/spinfreebase.cc:29:
/usr/local/include/TiledArray/tile_op/binary_wrapper.h:145:19: note: candidate: TiledArray::detail::BinaryWrapper<Op>::result_type TiledArray::detail::BinaryWrapper<Op>::operator()(TiledArray::detail::BinaryWrapper<Op>::left_type&&, TiledArray::detail::BinaryWrapper<Op>::right_type&&) const [with Op = TiledArray::Mult<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, true, true>; TiledArray::detail::BinaryWrapper<Op>::result_type = TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >; TiledArray::detail::BinaryWrapper<Op>::left_type = TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >; TiledArray::detail::BinaryWrapper<Op>::right_type = TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >]
       result_type operator()(left_type&& left, right_type&& right) const {
                   ^
/usr/local/include/TiledArray/tile_op/binary_wrapper.h:145:19: note:   no known conversion for argument 2 from 'const TiledArray::ZeroTensor' to 'TiledArray::detail::BinaryWrapper<TiledArray::Mult<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, true, true> >::right_type&& {aka TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >&&}'
/usr/local/include/TiledArray/tile_op/binary_wrapper.h:160:19: note: candidate: TiledArray::detail::BinaryWrapper<Op>::result_type TiledArray::detail::BinaryWrapper<Op>::operator()(const TiledArray::ZeroTensor&, TiledArray::detail::BinaryWrapper<Op>::right_type&&) const [with Op = TiledArray::Mult<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, true, true>; TiledArray::detail::BinaryWrapper<Op>::result_type = TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >; TiledArray::detail::BinaryWrapper<Op>::right_type = TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >]
       result_type operator()(const ZeroTensor& left, right_type&& right) const {
                   ^
/usr/local/include/TiledArray/tile_op/binary_wrapper.h:160:19: note:   no known conversion for argument 1 from 'TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >' to 'const TiledArray::ZeroTensor&'
/usr/local/include/TiledArray/tile_op/binary_wrapper.h:175:19: note: candidate: TiledArray::detail::BinaryWrapper<Op>::result_type TiledArray::detail::BinaryWrapper<Op>::operator()(TiledArray::detail::BinaryWrapper<Op>::left_type&&, const TiledArray::ZeroTensor&) const [with Op = TiledArray::Mult<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, true, true>; TiledArray::detail::BinaryWrapper<Op>::result_type = TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >; TiledArray::detail::BinaryWrapper<Op>::left_type = TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >] <near match>
       result_type operator()(left_type&& left, const ZeroTensor& right) const {
                   ^
/usr/local/include/TiledArray/tile_op/binary_wrapper.h:175:19: note:   conversion of argument 1 would be ill-formed:
In file included from /usr/local/include/TiledArray/expressions/binary_engine.h:30:0,
                 from /usr/local/include/TiledArray/expressions/add_engine.h:29,
                 from /usr/local/include/TiledArray/expressions/add_expr.h:29,
                 from /usr/local/include/TiledArray/expressions/tsr_expr.h:29,
                 from /usr/local/include/tiledarray.h:37,
                 from ../../../src/smith/tatensor.h:29,
                 from ../../../src/smith/tensor.h:45,
                 from ../../../src/smith/spinfreebase.cc:29:
```
This is what follows that error message

**Comment by justusc** [comment] 2015-12-10 18:48
I believe the errors you were seeing in the original code has been fixed.

**Comment by shiozaki** [comment] 2015-12-10 19:15
I am now having this error:
```
/usr/local/include/TiledArray/tensor/tensor.h:969:44: error: no match for 'operator*' (operand types are 'std::complex<double>' and 'const int')
           -> numeric_type { return (l * r) * factor; }, perm);
```

**Comment by justusc** [comment] 2015-12-10 19:28
One of the recent changes in TA is that the type of scaling factors are retained. Previously the type of scaling factors were converted to the type of the array elements. As a consequence, the operation you specified will fail because `std::complex<double> * int` is not supported. The fix is to change the scaling factor to a floating point type (i.e. `2.0` instead of `2`). Alternatively, if this is an unacceptable change, you can overload the multiplication operation for complex types.

**Comment by shiozaki** [comment] 2015-12-10 20:24
Yes, I added the overloaded multiplication and the code compiles and works as before. Look forward to the extension to block expressions.

**Comment by justusc** [comment] 2015-12-10 21:02
@shiozaki I have pushed the changes for conjugate operations with block expressions. Again, I still need to test this code for correctness, but please feel free to do some more testing.

**Comment by shiozaki** [comment] 2015-12-10 21:12
Thanks - I am gertting now this:
```
/usr/local/include/TiledArray/tile_op/contract_reduce.h:45:26: error: no matching function for call to 'gemm(TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::detail::ComplexConjugate<void>, TiledArray::math::GemmHelper)'
     typedef decltype(gemm(std::declval<Left>(), std::declval<Right>(),
```
```
/usr/local/include/TiledArray/tile_op/tile_interface.h:834:15: error: no matching function for call to 'TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >::gemm(const TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >&, const TiledArray::detail::ComplexConjugate<void>&, const TiledArray::math::GemmHelper&) const'
```

**Comment by justusc** [comment] 2015-12-10 21:21
The error seems to be coming from incorrect handling of conjugated expressions with contraction. A fix is on its way.

**Comment by justusc** [comment] 2015-12-11 21:54
I have pushed more changes that should fix your previous error. I also tested a simple matrix multiplication with complex conjugated arrays, and it compiled. The code still needs more testing of course.

**Comment by justusc** [comment] 2015-12-11 21:56
I still have not implemented complex conjugate as a general expression operations, so for now it can only be applied to arrays and block expressions. I will add support for contractions with other expression types soon; hopefully this weekend.

**Comment by shiozaki** [comment] 2015-12-11 23:18
thanks - I am getting this (and it looks strange):

```
/usr/local/include/TiledArray/tile_op/contract_reduce.h: In instantiation of 'class TiledArray::ContractReduce<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, std::complex<double> >':
/usr/local/include/TiledArray/expressions/cont_engine.h:104:15:   required from 'class TiledArray::expressions::ContEngine<TiledArray::expressions::MultEngine<TiledArray::expressions::BlkTsrEngine<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy> >, TiledArray::expressions::ScalBlkTsrEngine<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy>, double> > >'
/usr/local/include/TiledArray/expressions/mult_engine.h:120:11:   required from 'class TiledArray::expressions::MultEngine<TiledArray::expressions::BlkTsrEngine<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy> >, TiledArray::expressions::ScalBlkTsrEngine<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy>, double> >'
/usr/local/include/TiledArray/expressions/expr.h:416:7:   required from 'class TiledArray::expressions::Expr<TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy> >, TiledArray::expressions::ScalBlkTsrExpr<const TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy>, double> > >'
/usr/local/include/TiledArray/expressions/binary_expr.h:38:11:   required from 'class TiledArray::expressions::BinaryExpr<TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy> >, TiledArray::expressions::ScalBlkTsrExpr<const TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy>, double> > >'
/usr/local/include/TiledArray/expressions/mult_expr.h:58:11:   required from 'class TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy> >, TiledArray::expressions::ScalBlkTsrExpr<const TiledArray::DistArray<TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::DensePolicy>, double> >'
../../../src/smith/diagonal.cc:94:78:   required from here
/usr/local/include/TiledArray/tile_op/contract_reduce.h:45:26: error: no matching function for call to 'gemm(TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >, std::complex<double>, TiledArray::math::GemmHelper)'
     typedef decltype(gemm(std::declval<Left>(), std::declval<Right>(),
```

**Comment by justusc** [comment] 2015-12-11 23:23
Ok I'll take a look at it. Is it possible for you to provide a failing
example?

Sent from my iPhone

On Dec 11, 2015, at 6:18 PM, Toru Shiozaki <notifications@github.com> wrote:

thanks - I am getting this (and it looks strange):

/usr/local/include/TiledArray/tile_op/contract_reduce.h: In
instantiation of 'class
TiledArray::ContractReduce<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
std::complex<double> >':
/usr/local/include/TiledArray/expressions/cont_engine.h:104:15:
required from 'class
TiledArray::expressions::ContEngine<TiledArray::expressions::MultEngine<TiledArray::expressions::BlkTsrEngine<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy> >,
TiledArray::expressions::ScalBlkTsrEngine<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy>, double> > >'
/usr/local/include/TiledArray/expressions/mult_engine.h:120:11:
required from 'class
TiledArray::expressions::MultEngine<TiledArray::expressions::BlkTsrEngine<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy> >,
TiledArray::expressions::ScalBlkTsrEngine<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy>, double> >'
/usr/local/include/TiledArray/expressions/expr.h:416:7:   required
from 'class TiledArray::expressions::Expr<TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy> >,
TiledArray::expressions::ScalBlkTsrExpr<const
TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy>, double> > >'
/usr/local/include/TiledArray/expressions/binary_expr.h:38:11:
required from 'class
TiledArray::expressions::BinaryExpr<TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy> >,
TiledArray::expressions::ScalBlkTsrExpr<const
TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy>, double> > >'
/usr/local/include/TiledArray/expressions/mult_expr.h:58:11:
required from 'class
TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy> >,
TiledArray::expressions::ScalBlkTsrExpr<const
TiledArray::DistArray<TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::DensePolicy>, double> >'
../../../src/smith/diagonal.cc:94:78:   required from here
/usr/local/include/TiledArray/tile_op/contract_reduce.h:45:26: error:
no matching function for call to
'gemm(TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
TiledArray::Tensor<std::complex<double>,
Eigen::aligned_allocator<std::complex<double> > >,
std::complex<double>, TiledArray::math::GemmHelper)'
     typedef decltype(gemm(std::declval<Left>(), std::declval<Right>(),

—
Reply to this email directly or view it on GitHub
<https://github.com/ValeevGroup/tiledarray/issues/34#issuecomment-164075506>
.

**Comment by shiozaki** [comment] 2015-12-11 23:24
OK I will make it as small as possible - hold on.

**Comment by shiozaki** [comment] 2015-12-11 23:35
It appears that this simple program does not work.
```
#include <tiledarray.h> // for TiledArray library
#include <complex>

namespace TA = TiledArray;

using namespace std;

int main(int argc, char** argv) {
  // Initialize runtime
  madness::World& world = madness::initialize(argc, argv);

  // Construct tile boundary vector
  std::vector<std::size_t> aa{0,2,10};

  // Construct a set of TiledRange1's
  TiledArray::TiledRange1 tileaa(aa.begin(), aa.end());

  std::vector<TiledArray::TiledRange1> ranges1{tileaa, tileaa, tileaa, tileaa};

  // Construct the 2D TiledRange
  TA::TiledRange trange1(ranges1.begin(), ranges1.end());

  // Construct array objects.
  TA::Array<complex<double>,4> a(world, trange1);
  TA::Array<complex<double>,4> b(world, trange1);
  TA::Array<complex<double>,4> c(world, trange1);

  // Initialize a and b.
  a.fill_local(2.0);
  b.fill_local(3.0);
  c.fill_local(0.0);

  c("i,j,k,l") += b("i,j,l,m") * a("l,m,k,l"); 

  // Wait for all the computation to complete before exiting
  world.gop.fence();

  madness::finalize();
  return 0;
}
```
FYI
```
[shiozaki@zinc tiledarray]$ git log | head
commit 0425b89436206c1fd82d3535df6b8e8441f61bd6
Author: Justus Calvin <justusc@vt.edu>
Date:   Fri Dec 11 16:51:20 2015 -0500

    Removed more unused scalar typedefs from expressions.

commit 4480832621373382634c76ab4c6f3cdc04e4362d
Author: Justus Calvin <justusc@vt.edu>
Date:   Fri Dec 11 16:38:23 2015 -0500

[shiozaki@zinc tiledarray]$ git diff
diff --git a/configure b/configure
index 52504cf..71af158 100755
--- a/configure
+++ b/configure
@@ -43,6 +43,7 @@ Invoked as "configure cmake" it will download and install cmake into ./cmake dir
 
 Usage: '"$0"' [<options>...]
 Options: [defaults in brackets after descriptions]
+../configure --blas="-lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm" --prefix=/usr/local
 Configuration:
   --help                  print this message
   --prefix=               install prefix (CMAKE_INSTALL_PREFIX=)
```

**Comment by shiozaki** [comment] 2015-12-11 23:53
FYI: This in type_traits.h 
```
264 
265     template <typename T>
266     struct scalar_type<std::complex<T> > : public scalar_type<T> { };
```
makes
```
‘TiledArray::Tensor<std::complex<double>, Eigen::aligned_allocator<std::complex<double> > >::scalar_type {aka double}’
```
which breaks gemm.

**Comment by justusc** [comment] 2015-12-12 00:32
@shiozaki Thank you for your patients. The example you sent me is now compiling for me. I also was able to compile several different binary expression variants in that program using all combinations of operator and conjugate I could think of. I think that should be the last of the compile bugs.

**Comment by shiozaki** [comment] 2015-12-12 00:54
Thanks. It does now compile. However I am getting wrong answers from BAGEL/SMITH computation. There are multiple occasions where I used conj() in BAGEL. I will check to see which is responsible for this and report again.

**Comment by shiozaki** [comment] 2015-12-12 01:25
Sorry! It was my fault. The code is working. Thanks!

**Comment by justusc** [comment] 2015-12-12 01:45
No worries. Does this mean complex conjugates are working? This is great news!

If so, I think it is safe to extend conjugate operations to the other expression types.

**Comment by justusc** [comment] 2015-12-14 15:44
@shiozaki I just pushed more changes to TA for complex support. You can now use the `conj()` free function on any expression type. You can also use the `.conj()` member function to conjugate array and block expressions use the .conj() member function.

I also added some unit tests, so all expressions should be compiling now. I have not implemented any tests to check correctness yet, but I do not expect any issues since the most of the code is identical for both element types.

I think all the work for this issue has been completed so I am going to close this issue. If you experience any problems related to this complex conjugate, please feel free to reopen the issue or create a new one.

**Closed by justusc** 2015-12-14 15:44 UTC

**Comment by shiozaki** [comment] 2015-12-14 16:02
Thanks much!

Quick question - is the following
```cpp
a("...") += b("...").conj() * c("...");
```
mapping to single zgemm3m (when MKLi used) call?
```
zgemm3m_("C", "N", 1.0, b.., ..., c.., .., 0.0, a..., ...);
```
If I understood this is what Eigen's conj() does.

If not, I will open another issue related generally to performance. My TA code is 3x slower than the original hard-written code on 1 node 1 thread - except for the use of TA, everything must be identical (tiling etc). Don't question my testing environment :-) - I've talked to Ed as well.

**Comment by evaleev** [comment] 2015-12-14 16:44
@shiozaki zgemm3m is not used ... we are using MADNESS-provided cblas.h to simplify dependency management. Please open a zgemm3m-related issue for TA, I'll open the matching MADNESS issue.

**Comment by justusc** [comment] 2015-12-14 17:03
Matrix multiplication operations map to `ZGEMM`, not `ZGEMM3M`. We may be able to add this as an optional extension. Also, the complex conjugate is applied before calling `ZGEMM`. I know this is not optimal, but merging complex conjugate and matrix multiplication operations will require more work and modification of the expression parsing code. My first priority was to get the complex operations into a functional state, then add optimizations

As for performance, I suspect you are having issues with granularity of your parallelism. Specifically you need to make sure you have enough blocks so that there is enough parallelism in your code. If you have 4 blocks and 32 threads, your performance is going to be poor. Typically we see the best performance for contraction operations when there are more than two result blocks per core. In addition, you do not want to make your blocks too small, otherwise performance will suffer due to overhead. I would recommend blocks sizes between 2^14 and 2^16 elements.

Another possible improvement to performance is to use MKL 11.3 or later w/ TBB threading and MADNESS w/ TBB support. This will allow parallelism within a single `*GEMM` call. Unfortunately, I have not had a chance to try this version of MKL, it should help reduce the performance dependence on the number of blocks and block size. We also have additional code, not yet it into the master branch, which uses TBB to parallelize element-wise operations. I will try to get this code merged in the near future. With these changes you should see a significant improvement to performance.

**Comment by evaleev** [comment] 2015-12-14 17:44
@justusc The tests @shiozaki cites all use 1 compute thread so the block size *should* not be an issue

**Comment by justusc** [comment] 2015-12-14 17:58
OK, I missed the 1 thread part.

The performance should not be that much slower. Though block size can still play a significant roll in performance due to overhead. In your hand coded implementation, I would expect a much lower overhead with respect to block sizes. If the blocks are too small, your performance will almost certainly suffer. You should have at least 2^14 to 2^16 elements per block for good GEMM performance.

It might be possible that matrix multiplications are being mapped to Eigen, though I tried to make sure that did not happen for tensor contractions with two complex tensors. I will investigate this possibility.

**Comment by shiozaki** [comment] 2015-12-14 17:59
No, both (my original code and TA-based code) are using MKL BLAS, so that should not be the difference.

What is definitely different is that index permutation in the original code is optimized (as permutation can be computed at compile time).

**Comment by justusc** [comment] 2015-12-14 18:55
The index permutations in TA are very fast as well. Also, I have written them such that element-wise operations (addition, subtractions, scaling, etc.) are fused with permutations.

The difference in permutations might be that you may be doing more permutations than you expect, depending on the data layout. If you want to try to optimize the expressions, you can print an expression trace to see where permutations are being preformed. You can print the expression with the following code.
```C++
c("i,j,k,l") = 2.0 * (b("i,j,n,m") * a("n,m,k,l")) + b("j,i,n,m") * a("n,m,l,k").conj();
std::cout << c("i,j,k,l") << 2.0 * (b("i,j,n,m") * a("n,m,k,l")) + b("j,i,n,m") * a("n,l,m,k").conj();
```
Output:
```
(i, j, k, l) =
  [+] (i, j, k, l)
    [*] [2] (i, j, k, l)
      (i, j, n, m)
      (n, m, k, l)
    [P (i, j, k, l)] [*] (j, i, k, l)
      (j, i, n, m)
      [P (n, m, k, l)] [conj()] (n, l, m, k)
```
Here each line represents a single operation on a tensor. The [...] show the operations that are applied to the tensor. `[P (...)]` indicates a permutations. If there are no square brackets, then the tensor is unchanged in the expression evaluation. The (...) variables correspond to tensor variable annotations, or the output data ordering of an operation.

Note: Expression trace does not understand +=, -=, or *=.

In addition to permutations, the code may be generating some extra copies of data due to the way expressions are written. For example:
```C++
c("i,j,k,l") = 2.0 * b("i,j,n,m") * a("n,m,k,l"); // 1
c("i,j,k,l") = 2.0 * (b("i,j,n,m") * a("n,m,k,l")); // 2
c("i,j,k,l") = b("i,j,n,m") * a("n,m,k,l") * 2.0; // 3
```
will generate different operations. 2 and 3 are the same, but expression 1 will create an extra temporary because the `b` tensor is scaled before the contraction operation. This is due to the the order of operations in C++.


It may also be useful to profile the code to see were the time is spent.

**Comment by shiozaki** [comment] 2015-12-14 19:18
It must be that if you compute permutation at runtime, it should be more expensive than those computed at compile time.
TA
```
a("i,j,k,l") = b("k,l,i,j");
```
My hard-wired code (generated by SMITH) is
```
sort_indices<2,3,0,1,0,1,1,1>(a.data(), b.data(), n, n, n, n);
```
which is due to specialization mapped to
```
mkl_domatcopy('c', 't', n*n, n*n, 1.0, a.data(), n*n, b.data(), n*n);
```

The permutation patterns in the original SMITH code are the same as that in TCE (i.e., permute every tile at the destination), so we should be doing more permutations than you do.

One possible thing is that, since we do not have delta yet, all the RDM-like intermediates are computed by old code and copied to TA tensors. That should not be that much of the overhead, but who knows.

PS: SMITH always generate 3.
```
c("i,j,k,l") = b("i,j,n,m") * a("n,m,k,l") * 2.0; // 3
```
PPS: The most time is spent in residual formation of the MRCI equations, which means +/-/* of tensors (there is no complicated stuff in here).

**Comment by justusc** [comment] 2015-12-14 19:58
Your Smith code is what I expected from your description. You do need to pay some attention to permutations when using TA (data ordering of intermediates, order of operations, etc.) to avoid them whenever possible.

There is certainly some overhead associated with a runtime approach to permutations, but it is negligible relative to the cost data movement. There is also some extra overhead associated with permutation of tensors over transpose of a matrix. My permutation algorithm is designed to ensure in-order memory access within the permutation for both the input and output tensor. I expect the MKL function is doing the same thing. Therefore, both should perform equally well since the algorithm is memory bandwidth bound.

Another common pitfall is if you unintentionally do an outer product in a double (or high) contraction. For example:

```C++
d("i,j") = a("i,x") *   b("y,j") * c("x,y")  ; // BAD!
d("i,j") = a("i,x") * ( b("y,j") * c("x,y") ); // GOOD
```

Unfortunately, without seeing the your generated code or looking at profile data, it is impossible to say what the root cause of the slow performance is.

**Comment by shiozaki** [comment] 2015-12-14 20:09
They are all available online (TA relativistic MRCI code https://github.com/nubakery/bagel/tree/tiledarray/src/smith/relmrci, original is its master). But anyway I am not asking you to figure this out at this point. What I reported was that if one uses this in a straightforward way it did not perform well.

Yes, the SMITH generated code is a tree of binary operation, so the quote thing above will never happen...

**Comment by justusc** [comment] 2015-12-14 20:09
There is also the possibility that TA is creating more copies than it should in some instances.
