### ISSUE TITLE
assignment etc to BlkTsrExpr

### ISSUE THREAD

**Issue by shiozaki** [ValeevGroup/tiledarray#37] opened 2015-10-19 02:33 UTC
Because assignment, += and, -= are deleted, one cannot do this sort of operation.
```
a("a2,c1,a4,c3").block({2,0,2,0}, {4,1,4,1})
= b("x1,a2,c1,a4").block({1,2,0,2}, {2,4,1,4}) * c("c3,x1").block({0,1}, {1,2});
```
This use case is *very* common in MR theories because the target residual tensor has some super-structure, requiring us to use the block expressions for tensors on the left.

PS: @evaleev  this is what I meant in the email.

**Comment by justusc** [comment] 2015-10-19 02:50
This type of expression was not implemented by design. Your intent in this type of expression, I assume, is to assign multiple sub-blocks to construct the full array. The reason for this restriction is because internally `Array` data is treated as immutable, and such expressions would break this design.

I believe we can work around this limitation with a minor addition to the `Array` interface. Would something like the following, where each block of a can only be assigned once, fit your needs?
```c++
a_temp("a2,c1,a4,c3") = b("x1,a2,c1,a4").block({1,2,0,2}, {2,4,1,4}) * c("c3,x1").block({0,1}, {1,2});
a.set_block(a_temp, {2,0,2,0}, {4,1,4,1});
```

**Comment by shiozaki** [comment] 2015-10-19 03:13
Yes and no. The way I work with MR theories with TA is that I overwrite operator() in the derived class of TA::Array that knows about physical meaning of the index sub-spaces, so that depending on the letter "c", "x", and "a" it automatically gets the corresponding blocks via the block expressions.

If you are not familiar with MR theory, look at CASPT2 papers - there are 7-8 sectors in each T amplitude. But they have to be one tensor in order to use subspace linear/Davidoson diagonalization solvers.

Of course there should be a way to make as you suggested, and it will work (well everything works when it comes to programming), but I am reluctant at the moment. If this is you guys' design decision that won't change, close the issue. But again this is a very common use case.

**Comment by shiozaki** [comment] 2015-10-19 03:17
PS: what I do actually is always daxpy (or +=), and daxpy'ing happens many times to the same block.

**Comment by justusc** [comment] 2015-10-19 03:34
Another person in our lab was trying to do something similar to this. I agree that it is a fairly common pattern, but mutating tile data is tricky in TA due to internally immutable data rules. I am sure there is some way to accomplish your goal, it just might not be as elegant as you were envisioning. Most likely it will involve multiple steps.

I will leave the issue open for now as it is focused on an important use case. I think it would be helpful for you, me, and @evaleev to have a video conference to discuss the best way to resolve this issue.

**Comment by evaleev** [comment] 2015-10-19 03:49
>
> This type of expression was not implemented by design. Your intent in this
> type of expression, I assume, is to assign multiple sub-blocks to construct
> the full array. The reason for this restriction is because internally
> Array data is treated as immutable, and such expressions would break this
> design.
>
I believe we can work around this limitation with a minor addition to the
> Array interface. Would something like the following, where each block of
> a can only be assigned once, fit your needs?
>
> a_temp("a2,c1,a4,c3") = b("x1,a2,c1,a4").block({1,2,0,2}, {2,4,1,4}) * c("c3,x1").block({0,1}, {1,2});
> a.set_block(a_temp, {2,0,2,0}, {4,1,4,1});
>
>
Immutability is not necessarily violated by assigning to
a("a2,c1,a4,c3").block({2,0,2,0}, {4,1,4,1}) What prevents assignment to
a("a2,c1,a4,c3").block({2,0,2,0}, {4,1,4,1}) assignment to block from
testing for multiple assignment at runtime?

Internal immutability does not need to limit API. some violations of
contracts must be tested at runtime anyway.

**Comment by justusc** [comment] 2015-10-19 16:14
Detecting double assignment is trivial and not an issue. To clarify my previous statement. The barrier to block-update operation is indirectly the internal immutable data. More precisely, it is data consistency in a distributed and non-deterministic environment which lacks global barriers. The immutable data contract is there to ensure proper data consistency. Unfortunately, this does unavoidably impact the API because it is difficult to maintain data consistency with certain operations. We can go into the gritty details if you like.

**Comment by justusc** [comment] 2015-10-21 20:53
@shiozaki I just pushed a change that should enable this feature request. The new code will allow you to assign sub-blocks of an array as you described in you initial issue submission. It still needs testing, but please feel free to give it a try.

The caveat is that the `Array` on the left-hand side of the assignment operator must be **fully** initialize, i.e. all tiles must contain some data. For dense `Array` objects, you may simply fill the tiles with 0's (or with whatever data is appropriate). For example:
```c++
array.fill_local(0.0);
```
If you are using a sparse `Array`, you can fulfill this requirement by constructing the array with a shape that specifies all zero tiles. Subsequent block assignments will update the shape data appropriately.

**Comment by shiozaki** [comment] 2015-10-21 20:54
Thanks much! OK I will give it a try and let you know how it goes.

**Comment by justusc** [comment] 2015-10-21 20:59
@pchong90 I think you also asked for this feature for your CCSD(T) code. If you have need of it, can test it as well? It would be very helpful.

**Comment by shiozaki** [comment] 2015-10-21 21:31
This is what I am getting. Any ideas? This comes from block() in the LHS (if we remove it compiles). Tensors are dense.
```
/usr/local/include/TiledArray/expressions/expr.h:251:55: error: 'const array_type {aka const class TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy>}' has no member named 'shape'
             dist_eval.shape()), tsr.array().get_pmap());
```
from
```
 (*ta0)("c3,a4,c1,a2").block({0,0,0,0}, {1,2,1,2}) += (*ta1)("a4,c1,a2,x1").block({1,0,1,1}, {3,1,3,2}) * (*ta2)("x1,c3").block({0,0},{1,1});
```

**Comment by justusc** [comment] 2015-10-22 12:06
@shiozaki I pushed more changes this morning. The changes include a unit test for sub-block assignments and other bug fixes. Everything should compile now. Please give it another try and continue to report bugs here.

I will be adding more unit tests shortly.

**Comment by shiozaki** [comment] 2015-10-22 15:22
I have this now. This is because BlkTsrExpr::operator+= assumes that the LHS and RHS have the same template parameter D for Expr\<D\> (see line 275 of blk_tsr_expr.h), but in my case, they are different (RHS is MultExpr and D is MultExpr).  
```
../../../src/smith/CASPT2_gen5.cc:46:25: error: no match for 'operator+=' (operand types are 'TiledArray::expressions::BlkTsrExpr<const TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >' and 'TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<const TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >, TiledArray::expressions::BlkTsrExpr<const TiledArray::Array<double, 2u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> > >')
```

**Comment by justusc** [comment] 2015-10-22 15:38
It looks like the expression is breaking because the LHS is `BlkTsrExpr<const Array<...> >`. Notice the `const Array`. This should occurs if the Array object is const. If this is not the case please let me know.

Also, can you give me the expression and full error output (if array is not const)?

**Comment by shiozaki** [comment] 2015-10-22 15:47
Thanks - you were right. There was a const specifier in the operator() in the wrapper, which is now removed and I believe the LHS is not const. Now it is:
```
/usr/local/include/TiledArray/expressions/expr.h: In instantiation of 'void TiledArray::expressions::Expr< <template-parameter-1-1> >::eval_to(TiledArray::expressions::BlkTsrExpr<A>&) const [with A = TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy>; Derived = TiledArray::expressions::AddExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >, TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >, TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 2u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> > > >]':
/usr/local/include/TiledArray/expressions/blk_tsr_expr.h:258:9:   required from 'TiledArray::expressions::BlkTsrExpr< <template-parameter-1-1> >::BlkTsrExpr_& TiledArray::expressions::BlkTsrExpr< <template-parameter-1-1> >::operator=(const TiledArray::expressions::Expr<D>&) [with D = TiledArray::expressions::AddExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >, TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >, TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 2u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> > > >; A = TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy>; TiledArray::expressions::BlkTsrExpr< <template-parameter-1-1> >::BlkTsrExpr_ = TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >]'
/usr/local/include/TiledArray/expressions/blk_tsr_expr.h:268:25:   required from 'TiledArray::expressions::BlkTsrExpr< <template-parameter-1-1> >::BlkTsrExpr_& TiledArray::expressions::BlkTsrExpr< <template-parameter-1-1> >::operator+=(const TiledArray::expressions::Expr<D>&) [with D = TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >, TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 2u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> > >; A = TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy>; TiledArray::expressions::BlkTsrExpr< <template-parameter-1-1> >::BlkTsrExpr_ = TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >]'
../../../src/smith/CASPT2_gen5.cc:46:25:   required from here
/usr/local/include/TiledArray/expressions/expr.h:281:23: error: no matching function for call to 'TiledArray::expressions::Expr<TiledArray::expressions::AddExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >, TiledArray::expressions::MultExpr<TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> >, TiledArray::expressions::BlkTsrExpr<TiledArray::Array<double, 2u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy> > > > >::set_tile(TiledArray::Array<double, 4u, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy>&, TiledArray::Range::size_type, TiledArray::detail::DistEval<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::DensePolicy>::future, std::shared_ptr<TiledArray::math::Shift<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> >&) const'
               set_tile(result, blk_range.ordinal(index), dist_eval.get(index), shift_op);
```

**Comment by shiozaki** [comment] 2015-10-22 15:49
I am calling (ta0, ta1 and ta2 are my wrapper class objects)
```
(*ta0)("a2,c1,a4,c3") += (*ta1)("x1,a2,c1,a4") * (*ta2)("c3,x1");
```
and the definition of the operator() of my class is
```
auto operator()(const std::string& vars) -> decltype(TiledArray::Array<DataType,N>::operator()(vars).block(std::array<size_t,N>(), std::array<size_t, N>()))
```

**Comment by justusc** [comment] 2015-10-22 16:15
I added a contraction expression to the unit test, and fixed two more errors as a result. The changes have been pushed. I think your expression should compile now.

**Comment by shiozaki** [comment] 2015-10-22 19:11
Yes, it does compile. I still have a problem (getting "nan") but it looks like probably due to inconsistency between TA and SMITH tensors, and is not related to this issue.

**Comment by justusc** [comment] 2015-10-22 19:28
The sub-block assignment code does not alter the tile elements output by expressions. The main issue to watch out for is that the output tile ranges are correct, though I am fairly certain this should not be an issue. If you have assertions enable, this type of error should present itself very quickly. 

Since the new code seems to be working for you, I am going to close this issue. Please feel free to reopen it (or create a new issue) if you think you are encountering more related errors.

If you are having trouble using TA, please submit a question issue or email me directly. I recently added some features that should automate much of the process of moving data into TA.

**Closed by justusc** 2015-10-22 19:28 UTC
Labels: enhancement
